# ==============================================================================
# MagikOS Environment
# ==============================================================================

set $MAGIKOS_PATH /home/magikxiii/Projects/magikos
set $PATH /home/magikxiii/Projects/magikos/bin:/home/magikxiii/.local/bin:$PATH
